// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerhanApp.Data;

#nullable disable

namespace SerhanApp.Data.Migrations
{
    [DbContext(typeof(SerhanContext))]
    [Migration("20240711131223_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CannotLoginUntilDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequireReLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserApplicationUserRoleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationUserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ApplicationUserRoleId");

                    b.ToTable("ApplicationUserApplicationUserRoleMapping");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PasswordTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ApplicationUserPassword");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUserRole");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserRolePermissionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationUserRoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserRoleId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ApplicationUserRolePermissionMapping");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.Security.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserApplicationUserRoleMapping", b =>
                {
                    b.HasOne("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserApplicationUserRoleMapping")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserRole", "ApplicationUserRole")
                        .WithMany("ApplicationUserApplicationUserRoleMapping")
                        .HasForeignKey("ApplicationUserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("ApplicationUserRole");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserPassword", b =>
                {
                    b.HasOne("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserPasswords")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserRolePermissionMapping", b =>
                {
                    b.HasOne("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserRole", "ApplicationUserRole")
                        .WithMany("ApplicationUserRolePermissionMapping")
                        .HasForeignKey("ApplicationUserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerhanApp.Data.Entities.Security.Permission", "Permission")
                        .WithMany("ApplicationUserRolePermissionMapping")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserRole");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserApplicationUserRoleMapping");

                    b.Navigation("ApplicationUserPasswords");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.ApplicationUsers.ApplicationUserRole", b =>
                {
                    b.Navigation("ApplicationUserApplicationUserRoleMapping");

                    b.Navigation("ApplicationUserRolePermissionMapping");
                });

            modelBuilder.Entity("SerhanApp.Data.Entities.Security.Permission", b =>
                {
                    b.Navigation("ApplicationUserRolePermissionMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
